table sqantiBigGenePred
"gene models with SQANTI QC annotations"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Name or ID of item, ideally both human readable and unique"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;       "RGB value (use R,G,B string in input file)"
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Alternative/human readable name"
   string cdsStartStat; "Status of CDS start annotation (none, unknown, incomplete, or complete)"
   string cdsEndStat;   "Status of CDS end annotation (none, unknown, incomplete, or complete)"
   int[blockCount] exonFrames; "Exon frame {0,1,2}, or -1 if no frame for exon"
   string type;        "Transcript type"
   string geneName;    "Primary identifier for gene"
   string geneName2;   "Alternative/human readable gene name"
   string geneType;    "Gene type"
   
   int length; "SQUANTI3 QC length"
   int exons; "SQUANTI3 QC exons"
   string structural_category; "SQUANTI3 QC structural_category"
   string associated_gene; "SQUANTI3 QC associated_gene"
   string associated_transcript; "SQUANTI3 QC associated_transcript"
   string ref_length; "SQUANTI3 QC ref_length"
   string ref_exons; "SQUANTI3 QC ref_exons"
   string diff_to_TSS; "SQUANTI3 QC diff_to_TSS"
   string diff_to_TTS; "SQUANTI3 QC diff_to_TTS"
   string diff_to_gene_TSS; "SQUANTI3 QC diff_to_gene_TSS"
   string diff_to_gene_TTS; "SQUANTI3 QC diff_to_gene_TTS"
   string subcategory; "SQUANTI3 QC subcategory"
   string RTS_stage; "SQUANTI3 QC RTS_stage"
   string all_canonical; "SQUANTI3 QC all_canonical"
   string min_sample_cov; "SQUANTI3 QC min_sample_cov"
   string min_cov; "SQUANTI3 QC min_cov"
   string min_cov_pos; "SQUANTI3 QC min_cov_pos"
   string sd_cov; "SQUANTI3 QC sd_cov"
   string FL; "SQUANTI3 QC FL"
   string n_indels; "SQUANTI3 QC n_indels"
   string n_indels_junc; "SQUANTI3 QC n_indels_junc"
   string bite; "SQUANTI3 QC bite"
   string iso_exp; "SQUANTI3 QC iso_exp"
   string gene_exp; "SQUANTI3 QC gene_exp"
   string ratio_exp; "SQUANTI3 QC ratio_exp"
   string FSM_class; "SQUANTI3 QC FSM_class"
   string coding; "SQUANTI3 QC coding"
   string ORF_length; "SQUANTI3 QC ORF_length"
   string CDS_length; "SQUANTI3 QC CDS_length"
   string CDS_start; "SQUANTI3 QC CDS_start"
   string CDS_end; "SQUANTI3 QC CDS_end"
   string CDS_genomic_start; "SQUANTI3 QC CDS_genomic_start"
   string CDS_genomic_end; "SQUANTI3 QC CDS_genomic_end"
   string predicted_NMD; "SQUANTI3 QC predicted_NMD"
   string perc_A_downstream_TTS; "SQUANTI3 QC perc_A_downstream_TTS"
   string seq_A_downstream_TTS; "SQUANTI3 QC seq_A_downstream_TTS"
   string dist_to_CAGE_peak; "SQUANTI3 QC dist_to_CAGE_peak"
   string within_CAGE_peak; "SQUANTI3 QC within_CAGE_peak"
   string dist_to_polyA_site; "SQUANTI3 QC dist_to_polyA_site"
   string within_polyA_site; "SQUANTI3 QC within_polyA_site"
   string polyA_motif; "SQUANTI3 QC polyA_motif"
   string polyA_dist; "SQUANTI3 QC polyA_dist"
   string polyA_motif_found; "SQUANTI3 QC polyA_motif_found"
   lstring ORF_seq; "SQUANTI3 QC ORF_seq"
   string ratio_TSS; "SQUANTI3 QC ratio_TSS"
)
